name: lenguas
description: Saving indigenous languages
publish_to: 'none' # Do not change this line ever

version: 1.0.3+4005

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #  cupertino_icons: ^1.0.3
  #  http: ^0.13.3
  #  provider: ^4.3.3
  #  shared_preferences: ^2.0.7
  #  share:
  #  flutter_inappwebview: ^5.3.2 # TODO: migrate to latest version
  ##  liquid_swipe: ^2.1.0
  #  cached_network_image: ^3.1.0
  flutter_signin_button: ^2.0.0
  #  google_sign_in: ^5.0.7
  #  uuid: ^3.0.4
  #  google_fonts: ^2.1.0
  #  path_provider: ^2.0.2
  #  auto_size_text: ^2.1.0
  ##  settings_ui: ^1.0.0  TODO update or remove for good
  ##  system_settings: ^2.0.0 TODO update for good settings
  #  flutter_json_widget: ^1.0.1
  sentry_flutter: ^6.2.0
  #  # Firebase plugins
  firebase_core: ^1.5.0
  #  firebase_analytics: ^8.3.0
  firebase_auth: ^3.0.2
  #  cloud_firestore: ^2.5.0
  #  url_launcher: ^6.0.9
  flutter_facebook_auth: ^3.5.1
  #  google_api_availability: ^3.0.1
  #  ionicons: ^0.1.1
  #  package_info: ^2.0.2
  ##  video_player: ^2.1.14

  # -----------------------------------------
  # UI
  pagination_view: ^2.0.0
  ant_icons: ^2.0.0-nullsafety.0
  cached_network_image: ^3.0.0

  # Network
  graphql_flutter: ^5.0.0
  internet_connection_checker: ^0.0.1+1

  # Dart data class
  json_serializable: ^6.1.1
  freezed_annotation: ^1.1.0
  functional_enum_annotation: ^1.2.1

  # Dependency Injection
  get_it: ^7.1.3
  injectable: ^1.0.4

  # State management
  flutter_bloc: ^7.0.1

  # Caching
  hive: ^2.0.4

  # Misc
  dartz: ^0.10.0-nullsafety.2
  rxdart: ^0.26.0
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Code generators
  freezed: ^1.1.0
  functional_enum: ^1.1.3
  injectable_generator: ^1.4.1
  build_runner: ^2.0.4

  # Linting
  effective_dart: ^1.3.1

  # Testing
  bloc_test: ^8.0.2
  mocktail: ^0.2.0
  lint: ^1.0.0

flutter_icons:
  android: true
  ios: true
  image_path_android: "img/icon-round-new-trimmed.png"
  image_path_ios: "img/icon-full-new.png"
  adaptive_icon_background: "img/icon-bg-padded.png"
  adaptive_icon_foreground: "img/icon-fg-new-padded.png"

flutter:

  uses-material-design: true

  # Fonts
  fonts:
    - family: FredokaOne
      fonts:
        - asset: assets/fonts/google_fonts/FredokaOne-Regular.ttf

  # Assets
  assets:
    - assets/img/

